### ISSUE TITLE
ImportError: cannot import name 'six' from 'django.utils'

### ISSUE THREAD

**Issue by gianluigiruggeri** [jazzband/django-smart-selects#302]
Using last version I have the same issues as reported [here](https://stackoverflow.com/questions/59709646/django-smart-selects-on-django-version-3-0-1-error-importerror-cannot-import)

Is there a way to avoid this as code-fix?

**Comment by manelclos** [comment]
@gianluigiruggeri install from master branch:
```
pip install -e git+https://github.com/jazzband/django-smart-selects.git#egg=django-smart-selects
```

**Comment by JudiPuak** [comment]
hi manelclos

i can see that in the github repo, the db_fields.py is already updated 
from this:
```from django.utils import six```
to this:
```import six```

however, when i run pip install --upgrade django-smart-selects, it says:  requirement already up-to-date <1.5.4>
and yet my db_fields.py still says:
```from django.utils import six```

then i created a new virtual env and ran pip install django-smart-selects==1.5.4 to that virtualenv
yet the db_fields.py of the new installation still says:
```from django.utils import six```

could someone please help make the updated db_fields.py get installed in a fresh installation of django-smart-select?

yes, you gave that "pip install -e git+https......"
but a fresh installation without that extra command should install the updated db_fields.py, don't you think?
this is necessary so that we can simply include django-smart-selects==1.5.4 in requirements.txt for heroku and the updated db_fields.py will be guaranteed to be installed

thank you so much

jud

**Comment by manelclos** [comment]
@JudiPuak a new release is out: https://pypi.org/project/django-smart-selects/

Can you please try it out and let me know how it works?

**Comment by JudiPuak** [comment]
hi manelclos:

i just did a pip install django-smart-selects==1.5.6
and yes, the db_fields.py says:
```
import six
````
thank you so much
jud

**Comment by manelclos** [comment]
great, closing this issue.
